### ISSUE TITLE
Solved - installation error (v8 boolean & electron rebuild error)

### ISSUE THREAD

**Issue by Floffah** [arkenthera/electron-vibrancy#34]
When trying to install (using `npm install electron-vibrancy` or just cloning the library and running `npm i` inside electron-vibrancy) i get the error:
```
d:\projects\unfinished\app\better-file-explorer\node_modules\electron-vibrancy\src\vibrancy.cc(86): error C2660: 'v8::Value::BooleanValue': function does not take 0 arguments [D:\projects\unfinished\app\better-file-explorer\node_modules\electron-vibrancy\build\Vib
rancy.vcxproj]
  c:\users\...\appdata\local\node-gyp\cache\14.0.0\include\node\v8.h(2855): note: see declaration of 'v8::Value::BooleanValue' (compiling source file ..\src\Vibrancy.cc)
```

I tried: changing that line to `bool toggleState = toggleStateObj->BooleanValue(info.GetIsolate());` but i get: ` cannot convert argument 1 from 'v8::Isolate *' to 'v8::Local<v8::Context>'`

I also tried changing that line to `bool toggleState = toggleStateObj->BooleanValue(toggleStateObj);` but i get `cannot convert argument 1 from 'v8::Local<v8::Object>' to 'v8::Isolate *'`

I found that commenting out that line and line 92 seems to make it build without errors

It then install correctly but when running i get:
![](https://i.imgur.com/FsMQa9Y.png)
However
![](https://i.imgur.com/rk7akZt.png)

Ok so i fixed it by running:
```
npm i electron-rebuild --save-dev
npx electron-rebuild
```
It now works on Node 14.0.0

You can download my version by running `npm i electron-vibrancy-fixforlatest`

**Comment by thechickennagget** [comment]
Thanks
